baseURL = 'https://blog.aswinkm.dev/'
languageCode = 'en-us'
title = 'My Portfolio'
theme = 'anatole'

enableEmoji = true
enableRobotsTXT = true

copyright = "2020-{{ YEAR }}"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true


[params]
title = "Iam Aswin KM"
author = "Aswin KM"
description = "My portfolio"
profilePicture = "images/profile.JPG"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/aswin-km/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/aswinkm-tc"

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

