  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[main]]
	name = "Accomplishments"
	weight = 500
	identifier = "accomplishments"

	[[main]]
	name = "Awards"
	weight = 510
	identifier = "awards"
	url = "/awards/"
	parent = "accomplishments"
